package basecode;

/**
 * Sert à afficher le label d'une file JMS et un champ pour renseigner l'IP
 *
 * @author Yvan
 */
public class AdresseInputPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdresseInputPanel with file as JMS file
     *
     * @param file JMS file to input
     */
    public AdresseInputPanel(FilesJMS file) {
        initComponents();
        this.labelName.setText("File " + file.toString() + " : ");
        this.fieldIP.setText("localhost");
    }

    /**
     * Get the text from the IP field
     *
     * @return IP renseignée
     */
    public String getTextIP() {
        return this.fieldIP.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        fieldIP = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(370, 42));
        setMinimumSize(new java.awt.Dimension(370, 42));
        setPreferredSize(new java.awt.Dimension(370, 42));

        labelName.setLabelFor(fieldIP);
        labelName.setText("ServerName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(fieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(fieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldIP;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
