package basecode;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 * Dialog paramétrable d'entrée d'une chaîne
 *
 * @author Yvan
 */
public class CustomInputString extends javax.swing.JDialog {

    /**
     * Chaîne à retourner
     */
    private String entree;

    /**
     * Creates new form CustomInputIP
     *
     * @param label Texte du dialogue
     * @param defaultText Texte par défaut du champ
     * @param title Titre du dialogue
     */
    public CustomInputString(String label, String defaultText, String title) {
        super();
        initComponents();
        this.entree = defaultText;
        this.setTitle(title);
        this.labelInfos.setText(label);
        this.entreeField.setText(this.entree);
        this.setLocationRelativeTo(null);
        this.launchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                exitRetour();
            }
        });
        this.entreeField.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
                    exitRetour();
                }
            }
        });
    }

    /**
     * Termine la fenêtre et enregistre la chaîne affichée
     */
    public void exitRetour() {
        this.entree = entreeField.getText();
        setVisible(false);
        dispose();
    }

    /**
     * Affiche le dialogue et retourne la chaîne entrée à sa fermeture
     *
     * @return Chaîne renseignée
     */
    public String showDialog() {
        this.setVisible(true);
        return this.entree;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entreeField = new javax.swing.JTextField();
        launchButton = new javax.swing.JButton();
        labelInfos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        entreeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entreeField.setToolTipText("Entrez l'IP du serveur JMS");

        launchButton.setText("Lancer");

        labelInfos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfos.setLabelFor(entreeField);
        labelInfos.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(launchButton)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInfos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entreeField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(labelInfos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entreeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(launchButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entreeField;
    private javax.swing.JLabel labelInfos;
    private javax.swing.JButton launchButton;
    // End of variables declaration//GEN-END:variables
}
